apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: fruits-catalog
    group: com.github.lbroudoux.msa
    provider: fabric8
    version: 1.0.0-SNAPSHOT
  name: fruits-catalog
spec:
  replicas: 1
  selector:
    app: fruits-catalog
    group: com.github.lbroudoux.msa
    provider: fabric8
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: fruits-catalog
        group: com.github.lbroudoux.msa
        provider: fabric8
        version: 1.0.0-SNAPSHOT
    spec:
      initContainers:
      - name: vault-init
        image: quay.io/lbroudoux/ubi8:latest
        command:
          - "sh"
          - "-c"
          - >
            OCP_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
            curl -k --request POST --data '{"jwt": "'"$OCP_TOKEN"'", "role": "fruits-catalog"}' https://vault-fruits-catalog.apps.144.76.24.92.nip.io/v1/auth/kubernetes/login | jq -j '.auth.client_token' > /etc/vault/token;
            X_VAULT_TOKEN=$(cat /etc/vault/token);
            curl -k --header "X-Vault-Token: $X_VAULT_TOKEN" https://vault-fruits-catalog.apps.144.76.24.92.nip.io/v1/database/creds/fruit-catalog-role > /etc/app/creds.json;
            echo "spring.data.mongodb.uri=mongodb://$(jq -j '.data.username' /etc/app/creds.json):$(jq -j '.data.password' /etc/app/creds.json)@mongodb/sampledb" > /etc/app/application.properties;
            cp /etc/app/application.properties /deployments/config/application.properties
        volumeMounts:
        - name: app-creds
          mountPath: /etc/app
        - name: vault-token
          mountPath: /etc/vault
        - name: app-config
          mountPath: /deployments/config  
      containers:
        - name: vault-lease-refresher
          image: quay.io/lbroudoux/ubi8:latest
          command:
            - "sh"
            - "-c"
            - >
              X_VAULT_TOKEN=$(cat /etc/vault/token);
              VAULT_LEASE_ID=$(cat /etc/app/creds.json | jq -j '.lease_id');
              while true; do
                curl -k --request PUT --header "X-Vault-Token: $X_VAULT_TOKEN" --data '{"lease_id": "'"$VAULT_LEASE_ID"'", "increment": 3600}' https://vault-fruits-catalog.apps.144.76.24.92.nip.io/v1/sys/leases/renew;
                sleep 3600;
              done
          lifecycle:
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    X_VAULT_TOKEN=$(cat /etc/vault/token);
                    VAULT_LEASE_ID=$(cat /etc/app/creds.json | jq -j '.lease_id');
                    curl -k --request PUT --header "X-Vault-Token: $X_VAULT_TOKEN" --data '{"lease_id": "'"$VAULT_LEASE_ID"'"}' https://vault-fruits-catalog.apps.144.76.24.92.nip.io/v1/sys/leases/revoke;
          volumeMounts:
            - name: app-creds
              mountPath: /etc/app
            - name: vault-token
              mountPath: /etc/vault
        - env:
            - name: KEYCLOAK_URL
              value: 'https://keycloak-fruits-catalog.apps.144.76.24.92.nip.io/auth'
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: >-
            docker-registry.default.svc:5000/fruits-catalog/fruits-catalog:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: spring-boot
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: '1'
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
          - name: app-creds
            mountPath: /etc/app
          - name: vault-token
            mountPath: /etc/vault
          - name: app-config
            mountPath: /deployments/config
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: fruits-catalog-vault
      serviceAccountName: fruits-catalog-vault
      volumes:
      - name: app-creds
        emptyDir: {}
      - name: app-config
        emptyDir: {}
      - name: vault-token
        emptyDir: {}
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - spring-boot
        from:
          kind: ImageStreamTag
          name: 'fruits-catalog:latest'
          namespace: fruits-catalog
      type: ImageChange

